### ISSUE TITLE
Support for uploading files through API using filename instead of path

### ISSUE THREAD

**Issue by roady001** [fiberpunk1/Beam-ESP32#13]
Uploading a file to the API proved to be challenging by Postman and NodeJS. The 'filename' is expected to be the full path (which is basically just a '/' prefix as files are uploaded to the root), instead of the actual filename. I believe this is not implemented correctly as filename is distinctively different from path. Both Postman and NodeJS won't allow this or if you try to force it, just ignore the '/' which fails the upload.

I updated the firmware myself to prepend a '/' in front of the filename. Pull request is in https://github.com/fiberpunk1/Beam-ESP32/pull/12. I'm sure others would appreciate this as well. 

I've created a nodeJS script that monitors a folder and automatically starts the print when a gcode file is dropped inside of that folder. This is much easier then manually having to do these steps through the webinterface. If the firmware is updated with my pull request, I can also make my script open-source for others to use.

**Comment by fiber-punk** [comment]
Thanks, it has been merged
