### ISSUE TITLE
Incorrect year & name for Prusa MK3s firmware (not 2023-02-02-2009-PRUSA-MK3S when following the guide links)

### ISSUE THREAD

**Issue by vtjballeng** [fiberpunk1/Beam-ESP32#19]
The Fiberpunk website says to expect the version:

> [Update Guide](https://docs.google.com/presentation/d/16Nf5uYkNyQBRbagg_cUlCnZcxTsM7C5II71hJjXmGPo/edit?usp=sharing) for Prusa MK3 latest firmware version 2023-02-02-2009-PRUSA-MK3S

When following the guide link I see a 2022 bin file.

![image](https://user-images.githubusercontent.com/12535732/233271960-95e05dc1-9571-474a-8727-73c97100f9ef.png)

This is confusing as it's not the expected version. 

![image](https://user-images.githubusercontent.com/12535732/233271832-8930d312-f566-41d0-846d-6f08102831e3.png)

![image](https://user-images.githubusercontent.com/12535732/233271538-f86e1d1d-1cb8-44a4-85cd-e80ff304cf3c.png)

https://github.com/fiberpunk1/Beam-ESP32/releases

**Comment by fiber-punk** [comment]
Thanks reminding, have  fix the doc and release firmware name
