### ISSUE TITLE
Display more helpful error messages

### ISSUE THREAD

**Issue by ammgws** [fiberpunk1/Beam-ESP32#7]
When using the web UI sometimes there are error messages like this (e.g. unmount SD card then click update filesystem):

![image](https://user-images.githubusercontent.com/20397027/189474654-3fe280ec-b566-406e-9643-7875db015aaf.png)

Is there any reason why this message can't be expanded to provide more info?

e.g. `NOT DIR` is explained in https://github.com/fiberpunk1/NodeWebPage/blob/main/NodeWebAPI.md but it would be better to have that in the Web UI itself

**Comment by fiber-punk** [comment]
1.0.6 webpage have added some operation tips for error info.
The code related to the webpage is migrated to this repository.
here close this issue first.
